DROP TABLE IF EXISTS `cal_backgrounds`;
DROP TABLE IF EXISTS `cal_calendars`;
DROP TABLE IF EXISTS `cal_events`;
DROP TABLE IF EXISTS `cal_participants`;
DROP TABLE IF EXISTS `cal_views`;
DROP TABLE IF EXISTS `cal_exceptions`;
DROP TABLE IF EXISTS `cal_views_calendars`;
DROP TABLE IF EXISTS `go_links_1`;
DROP TABLE IF EXISTS `cal_settings`;
