SET DATABASE DEFAULT TABLE TYPE MEMORY;

DROP TABLE translation IF EXISTS;
DROP TABLE language IF EXISTS;
DROP TABLE template IF EXISTS;
DROP TABLE template_type IF EXISTS;

CREATE SCHEMA mbuni;
CREATE TABLE mbuni.language (language_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name VARCHAR(100) NOT NULL, subname VARCHAR(100), code VARCHAR(100) NOT NULL, subcode VARCHAR(100));
CREATE TABLE mbuni.translation (translation_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, unique_name VARCHAR(100) NOT NULL, language_fk BIGINT NOT NULL, translation VARCHAR(100) NOT NULL, FOREIGN KEY (language_fk) REFERENCES mbuni.language(language_id) ON DELETE CASCADE);
CREATE TABLE mbuni.template_type (template_type_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name VARCHAR(100) NOT NULL, UNIQUE(name));
CREATE TABLE mbuni.template (template_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name VARCHAR(100) NOT NULL, auth VARCHAR(100), value VARCHAR(100) NOT NULL, template_type_fk BIGINT NOT NULL, template_fk BIGINT, FOREIGN KEY (template_fk) REFERENCES template(template_id) ON DELETE CASCADE, FOREIGN KEY (template_type_fk) REFERENCES mbuni.template_type(template_type_id) ON DELETE CASCADE);





COMMIT;


