DROP TABLE IF EXISTS `ab_addressbooks`;
DROP TABLE IF EXISTS `ab_companies`;
DROP TABLE IF EXISTS `ab_contacts`;
DROP TABLE IF EXISTS `cf_2`;
DROP TABLE IF EXISTS `cf_3`;
DROP TABLE IF EXISTS `go_links_2`;
DROP TABLE IF EXISTS `go_links_3`;